'use strict';
const getHash = require('../helpers/getHash');

module.exports = {
    up: async (queryInterface, Sequelize) => {
        return queryInterface.bulkInsert('reader', [
            {
                name: 'Серёжа Соснов',
                password: await getHash('1'),
                groupId: 1,
                login: 'serj',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Алексей Терешенко',
                password: await getHash('2'),
                groupId: 1,
                login: 'alex',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Мари Федина',
                password: await getHash('3'),
                groupId: 1,
                login: 'mary',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Сахиб Исмаилов',
                password: await getHash('4'),
                groupId: 1,
                login: 'somebody',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Илья Щербаков',
                password: await getHash('5'),
                groupId: 1,
                login: 'ilya',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Александр Тихонов',
                password: await getHash('6'),
                groupId: 1,
                login: 'alex',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Ермолай Чебыкин',
                password: await getHash('7'),
                groupId: 1,
                login: 'erm',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Катя Трофимова',
                password: await getHash('8'),
                groupId: 1,
                login: 'kate',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Сергей Шутов',
                password: await getHash('9'),
                groupId: 1,
                login: 'serjSh',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Алан Тедеев',
                password: await getHash('10'),
                groupId: 1,
                login: 'alan_rahmat_hinkal_sila',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Никита Черепанов',
                password: await getHash('11'),
                groupId: 1,
                login: 'nik',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Евгений Цоль',
                password: await getHash('12'),
                groupId: 1,
                login: 'evgen',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Абдуджалил Джумаев',
                password: await getHash('13'),
                groupId: 1,
                login: 'abdudjalil',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Иосиф Стальнов',
                password: await getHash('14'),
                groupId: 1,
                login: 'iosif',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Гриша Рухлов',
                password: await getHash('15'),
                groupId: 1,
                login: 'grisha',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'Анастасия Чумакина',
                password: await getHash('16'),
                groupId: 1,
                login: 'nasti',
                createdAt: new Date(),
                updatedAt: new Date(),
            },
        ]);
    },

    down: async (queryInterface, Sequelize) => {
        return queryInterface.bulkDelete('reader', null, {});
    },
};
